FROM docker.io/maven:3.6.3-openjdk-11-slim as builder

ADD . .

RUN mvn -DskipTests clean package

FROM registry.access.redhat.com/ubi8/openjdk-11

COPY --from=builder target/quarkus-app /deployments/