---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hybrid-cloud-frontend
  annotations:
    image.openshift.io/triggers: '[{"from":{"kind":"ImageStreamTag","name":"hybrid-cloud-frontend:v2"},"fieldPath":"spec.template.spec.containers[?(@.name==\"hybrid-cloud-frontend\")].image"}]'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hybrid-cloud-frontend
  template:
    metadata:
      labels:
        app: hybrid-cloud-frontend
    spec:
      serviceAccountName: hybrid-cloud-demo-sa
      containers:
        - name: hybrid-cloud-frontend
          image: hybrid-cloud-demo-frontend
          imagePullPolicy: Always
          env:
            - name: COM_REDHAT_DEVELOPERS_DEMO_SERVICE_BACKENDSERVICECLIENT_MP_REST_URL
              value: http://hybrid-cloud-backend:8080
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          resources:
            limits:
              memory: 1200Mi
              cpu: 750m
            requests:
              memory: 500Mi
              cpu: 500m
          livenessProbe:
            httpGet:
              path: /health/live
              port: 8080
              scheme: HTTP
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 8080
              scheme: HTTP
